language: php
php:
- '7.0'
- '7.1'
- '7.2'
- '7.3'
before_install: 
- mkdir openapi-generator
- curl https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/bin/utils/openapi-generator-cli.sh > openapi-generator/openapi-generator-cli
- chmod +x openapi-generator/openapi-generator-cli 
script:
- wget https://raw.githubusercontent.com/gyselroth/balloon/master/src/app/Balloon.App.Api/swagger.yml -O swagger.yml
- wget https://raw.githubusercontent.com/gyselroth/balloon/master/src/app/Balloon.App.Api/openapi.yml -O openapi.yml
- make
after_success:
- git config --global user.email "sahli@gyselroth.com"
- git config --global user.name "Travis CI"
- git add src/*; git add src/*.yml
- git commit --message "Travis build: $TRAVIS_BUILD_NUMBER"
- git push --quiet --set-upstream master master
