<?php
/**
 * BalloonAppNotificationsV2ApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Balloon\Sdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * balloon API
 *
 * balloon API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Balloon\Sdk;

use \Balloon\Sdk\Configuration;
use \Balloon\Sdk\ApiException;
use \Balloon\Sdk\ObjectSerializer;

/**
 * BalloonAppNotificationsV2ApiTest Class Doc Comment
 *
 * @category Class
 * @package  Balloon\Sdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BalloonAppNotificationsV2ApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteNotification
     *
     * Delete a notification.
     *
     */
    public function testDeleteNotification()
    {
    }

    /**
     * Test case for getMyNotifications
     *
     * Get my nofitifications.
     *
     */
    public function testGetMyNotifications()
    {
    }

    /**
     * Test case for getNotification
     *
     * Get a single notification.
     *
     */
    public function testGetNotification()
    {
    }

    /**
     * Test case for postNotification
     *
     * Send notification.
     *
     */
    public function testPostNotification()
    {
    }

    /**
     * Test case for sendBroadcast
     *
     * Send notification to all users.
     *
     */
    public function testSendBroadcast()
    {
    }

    /**
     * Test case for sendMail
     *
     * Send mail.
     *
     */
    public function testSendMail()
    {
    }

    /**
     * Test case for subscribeNode
     *
     * Receive node updates.
     *
     */
    public function testSubscribeNode()
    {
    }
}
