<?php

declare(strict_types=1);

/**
 * balloon
 *
 * @copyright   Copryright (c) 2019 gyselroth GmbH (https://gyselroth.com)
 * @license     MIT https://opensource.org/licenses/MIT
 */

/**
 * balloon API.
 *
 * balloon API
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Balloon\Sdk;

/**
 * BalloonAppOfficeV2ApiTest Class Doc Comment.
 *
 * @category Class
 *
 * @author   Swagger Codegen team
 *
 * @see     https://github.com/swagger-api/swagger-codegen
 */
class BalloonAppOfficeV2ApiTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()
    {
    }

    /**
     * Test case for createDocument.
     *
     * .
     */
    public function testCreateDocument()
    {
    }

    /**
     * Test case for createSession.
     *
     * Create new session for a document.
     */
    public function testCreateSession()
    {
    }

    /**
     * Test case for deleteSession.
     *
     * Delete a running session. If more members are active in the requested session than only the membership gets removed. The session gets completely removed if only one member exists..
     */
    public function testDeleteSession()
    {
    }

    /**
     * Test case for getDocument.
     *
     * Retreive office document.
     */
    public function testGetDocument()
    {
    }

    /**
     * Test case for getWopiDocument.
     *
     * Get document session information including document owner, session user and document size.
     */
    public function testGetWopiDocument()
    {
    }

    /**
     * Test case for getWopiDocumentContent.
     *
     * Get document contents.
     */
    public function testGetWopiDocumentContent()
    {
    }

    /**
     * Test case for joinSession.
     *
     * Join running session.
     */
    public function testJoinSession()
    {
    }

    /**
     * Test case for updateWopiDocuemntContent.
     *
     * Save document contents.
     */
    public function testUpdateWopiDocuemntContent()
    {
    }
}
