<?php
/**
 * BalloonAppConvertV2ApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Balloon\Sdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * balloon API
 *
 * balloon API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Balloon\Sdk;

use \Balloon\Sdk\Configuration;
use \Balloon\Sdk\ApiException;
use \Balloon\Sdk\ObjectSerializer;

/**
 * BalloonAppConvertV2ApiTest Class Doc Comment
 *
 * @category Class
 * @package  Balloon\Sdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BalloonAppConvertV2ApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addSlave
     *
     * Add new convert slave.
     *
     */
    public function testAddSlave()
    {
    }

    /**
     * Test case for deleteSlave
     *
     * Delete slave.
     *
     */
    public function testDeleteSlave()
    {
    }

    /**
     * Test case for getSlave
     *
     * Get single slave.
     *
     */
    public function testGetSlave()
    {
    }

    /**
     * Test case for getSlaves
     *
     * Get existing convert slaves.
     *
     */
    public function testGetSlaves()
    {
    }

    /**
     * Test case for getSupportedFormats
     *
     * Get supported file formats to convert to (formats do vary between files).
     *
     */
    public function testGetSupportedFormats()
    {
    }
}
