<?php

declare(strict_types=1);

/**
 * balloon
 *
 * @copyright   Copryright (c) 2019 gyselroth GmbH (https://gyselroth.com)
 * @license     MIT https://opensource.org/licenses/MIT
 */

/**
 * balloon API.
 *
 * balloon API
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Balloon\Sdk;

/**
 * ConvertV2ApiTest Class Doc Comment.
 *
 * @category Class
 *
 * @author   Swagger Codegen team
 *
 * @see     https://github.com/swagger-api/swagger-codegen
 */
class ConvertV2ApiTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()
    {
    }

    /**
     * Test case for addSlave.
     *
     * Add new convert slave.
     */
    public function testAddSlave()
    {
    }

    /**
     * Test case for deleteSlave.
     *
     * Delete slave.
     */
    public function testDeleteSlave()
    {
    }

    /**
     * Test case for getSlave.
     *
     * Get single slave.
     */
    public function testGetSlave()
    {
    }

    /**
     * Test case for getSlaves.
     *
     * Get existing convert slaves.
     */
    public function testGetSlaves()
    {
    }

    /**
     * Test case for getSupportedFormats.
     *
     * Get supported file formats to convert to (formats do vary between files).
     */
    public function testGetSupportedFormats()
    {
    }
}
