<?php

declare(strict_types=1);

/**
 * balloon
 *
 * @copyright   Copryright (c) 2019 gyselroth GmbH (https://gyselroth.com)
 * @license     MIT https://opensource.org/licenses/MIT
 */

/**
 * balloon API.
 *
 * balloon API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Balloon\Sdk;

use PHPUnit\Framework\TestCase;

/**
 * NotificationV2ApiTest Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */
class NotificationV2ApiTest extends TestCase
{
    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()
    {
    }

    /**
     * Test case for deleteNotification.
     *
     * Delete a notification.
     */
    public function testDeleteNotification()
    {
    }

    /**
     * Test case for getMyNotifications.
     *
     * Get my nofitifications.
     */
    public function testGetMyNotifications()
    {
    }

    /**
     * Test case for getNotification.
     *
     * Get a single notification.
     */
    public function testGetNotification()
    {
    }

    /**
     * Test case for postNotification.
     *
     * Send notification.
     */
    public function testPostNotification()
    {
    }

    /**
     * Test case for sendBroadcast.
     *
     * Send notification to all users.
     */
    public function testSendBroadcast()
    {
    }

    /**
     * Test case for sendMail.
     *
     * Send mail.
     */
    public function testSendMail()
    {
    }

    /**
     * Test case for subscribeNode.
     *
     * Receive node updates.
     */
    public function testSubscribeNode()
    {
    }
}
