<?php

declare(strict_types=1);

/**
 * balloon
 *
 * @copyright   Copryright (c) 2019 gyselroth GmbH (https://gyselroth.com)
 * @license     MIT https://opensource.org/licenses/MIT
 */

/**
 * balloon API.
 *
 * balloon API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Balloon\Sdk;

use PHPUnit\Framework\TestCase;

/**
 * WopiV2ApiTest Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */
class WopiV2ApiTest extends TestCase
{
    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()
    {
    }

    /**
     * Test case for createDocument.
     *
     * .
     */
    public function testCreateDocument()
    {
    }

    /**
     * Test case for getWopiDocument.
     *
     * Get document session information including document owner, session user and document size.
     */
    public function testGetWopiDocument()
    {
    }

    /**
     * Test case for getWopiDocumentContent.
     *
     * Get document contents.
     */
    public function testGetWopiDocumentContent()
    {
    }

    /**
     * Test case for updateWopiDocuemntContent.
     *
     * Save document contents.
     */
    public function testUpdateWopiDocuemntContent()
    {
    }
}
