<?php

declare(strict_types=1);

/**
 * balloon
 *
 * @copyright   Copryright (c) 2019 gyselroth GmbH (https://gyselroth.com)
 * @license     MIT https://opensource.org/licenses/MIT
 */

/**
 * balloon API.
 *
 * balloon API
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Balloon\Sdk;

/**
 * BalloonAppNotfificationMailTest Class Doc Comment.
 *
 * @category    Class
 * @description Mail
 *
 * @author      Swagger Codegen team
 *
 * @see        https://github.com/swagger-api/swagger-codegen
 */
class BalloonAppNotfificationMailTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Setup before running any test case.
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()
    {
    }

    /**
     * Test "BalloonAppNotfificationMail".
     */
    public function testBalloonAppNotfificationMail()
    {
    }

    /**
     * Test attribute "receiver".
     */
    public function testPropertyReceiver()
    {
    }

    /**
     * Test attribute "subject".
     */
    public function testPropertySubject()
    {
    }

    /**
     * Test attribute "body".
     */
    public function testPropertyBody()
    {
    }
}
