<?php
/**
 * BalloonAppOfficeWopiDocumentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Balloon\Sdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * balloon API
 *
 * balloon API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Balloon\Sdk;

/**
 * BalloonAppOfficeWopiDocumentTest Class Doc Comment
 *
 * @category    Class
 * @description WOPI document https://wopi.readthedocs.io/projects/wopirest/en/latest/files/CheckFileInfo.html
 * @package     Balloon\Sdk
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BalloonAppOfficeWopiDocumentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BalloonAppOfficeWopiDocument"
     */
    public function testBalloonAppOfficeWopiDocument()
    {
    }

    /**
     * Test attribute "base_file_name"
     */
    public function testPropertyBaseFileName()
    {
    }

    /**
     * Test attribute "size"
     */
    public function testPropertySize()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "owner_id"
     */
    public function testPropertyOwnerId()
    {
    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "user_friendly_name"
     */
    public function testPropertyUserFriendlyName()
    {
    }

    /**
     * Test attribute "user_can_write"
     */
    public function testPropertyUserCanWrite()
    {
    }

    /**
     * Test attribute "post_message_origin"
     */
    public function testPropertyPostMessageOrigin()
    {
    }
}
