<?php

declare(strict_types=1);

/**
 * balloon
 *
 * @copyright   Copryright (c) 2019 gyselroth GmbH (https://gyselroth.com)
 * @license     MIT https://opensource.org/licenses/MIT
 */

/**
 * balloon API.
 *
 * balloon API
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Balloon\Sdk;

/**
 * CoreV2CollectionTest Class Doc Comment.
 *
 * @category    Class
 * @description A collection can hold an unlimited number of child nodes.
 *
 * @author      Swagger Codegen team
 *
 * @see        https://github.com/swagger-api/swagger-codegen
 */
class CoreV2CollectionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Setup before running any test case.
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()
    {
    }

    /**
     * Test "CoreV2Collection".
     */
    public function testCoreV2Collection()
    {
    }

    /**
     * Test attribute "_links".
     */
    public function testPropertyLinks()
    {
    }

    /**
     * Test attribute "id".
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "created".
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "changed".
     */
    public function testPropertyChanged()
    {
    }

    /**
     * Test attribute "deleted".
     */
    public function testPropertyDeleted()
    {
    }

    /**
     * Test attribute "name".
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "mime".
     */
    public function testPropertyMime()
    {
    }

    /**
     * Test attribute "readonly".
     */
    public function testPropertyReadonly()
    {
    }

    /**
     * Test attribute "directory".
     */
    public function testPropertyDirectory()
    {
    }

    /**
     * Test attribute "meta".
     */
    public function testPropertyMeta()
    {
    }

    /**
     * Test attribute "size".
     */
    public function testPropertySize()
    {
    }

    /**
     * Test attribute "path".
     */
    public function testPropertyPath()
    {
    }

    /**
     * Test attribute "access".
     */
    public function testPropertyAccess()
    {
    }

    /**
     * Test attribute "parent".
     */
    public function testPropertyParent()
    {
    }

    /**
     * Test attribute "share".
     */
    public function testPropertyShare()
    {
    }

    /**
     * Test attribute "shareowner".
     */
    public function testPropertyShareowner()
    {
    }

    /**
     * Test attribute "subscription".
     */
    public function testPropertySubscription()
    {
    }

    /**
     * Test attribute "subscription_exclude_me".
     */
    public function testPropertySubscriptionExcludeMe()
    {
    }

    /**
     * Test attribute "sharelink_has_password".
     */
    public function testPropertySharelinkHasPassword()
    {
    }
}
