<?php

declare(strict_types=1);

/**
 * balloon
 *
 * @copyright   Copryright (c) 2019 gyselroth GmbH (https://gyselroth.com)
 * @license     MIT https://opensource.org/licenses/MIT
 */

/**
 * balloon API.
 *
 * balloon API
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Balloon\Sdk;

/**
 * CoreV2OAuth2TokenTest Class Doc Comment.
 *
 * @category    Class
 * @description OAUTH2 access token response according RFC6749 https://tools.ietf.org/html/rfc6749#section-4.3.3
 *
 * @author      Swagger Codegen team
 *
 * @see        https://github.com/swagger-api/swagger-codegen
 */
class CoreV2OAuth2TokenTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Setup before running any test case.
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()
    {
    }

    /**
     * Test "CoreV2OAuth2Token".
     */
    public function testCoreV2OAuth2Token()
    {
    }

    /**
     * Test attribute "access_token".
     */
    public function testPropertyAccessToken()
    {
    }

    /**
     * Test attribute "expires_in".
     */
    public function testPropertyExpiresIn()
    {
    }

    /**
     * Test attribute "token_type".
     */
    public function testPropertyTokenType()
    {
    }

    /**
     * Test attribute "scope".
     */
    public function testPropertyScope()
    {
    }

    /**
     * Test attribute "refresh_token".
     */
    public function testPropertyRefreshToken()
    {
    }
}
