<?php

declare(strict_types=1);

/**
 * balloon
 *
 * @copyright   Copryright (c) 2019 gyselroth GmbH (https://gyselroth.com)
 * @license     MIT https://opensource.org/licenses/MIT
 */

/**
 * balloon API.
 *
 * balloon API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Balloon\Sdk;

use PHPUnit\Framework\TestCase;

/**
 * CoreV2ResourceListTest Class Doc Comment.
 *
 * @category    Class
 * @description CoreV2ResourceList
 *
 * @author      OpenAPI Generator team
 *
 * @see        https://openapi-generator.tech
 */
class CoreV2ResourceListTest extends TestCase
{
    /**
     * Setup before running any test case.
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()
    {
    }

    /**
     * Test "CoreV2ResourceList".
     */
    public function testCoreV2ResourceList()
    {
    }

    /**
     * Test attribute "_links".
     */
    public function testPropertyLinks()
    {
    }

    /**
     * Test attribute "kind".
     */
    public function testPropertyKind()
    {
    }

    /**
     * Test attribute "count".
     */
    public function testPropertyCount()
    {
    }

    /**
     * Test attribute "total".
     */
    public function testPropertyTotal()
    {
    }
}
