<?php

declare(strict_types=1);

/**
 * balloon
 *
 * @copyright   Copryright (c) 2019 gyselroth GmbH (https://gyselroth.com)
 * @license     MIT https://opensource.org/licenses/MIT
 */

/**
 * balloon API.
 *
 * balloon API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Balloon\Sdk;

use PHPUnit\Framework\TestCase;

/**
 * CoreV2UserTest Class Doc Comment.
 *
 * @category    Class
 * @description A user is used to access the server.
 *
 * @author      OpenAPI Generator team
 *
 * @see        https://openapi-generator.tech
 */
class CoreV2UserTest extends TestCase
{
    /**
     * Setup before running any test case.
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()
    {
    }

    /**
     * Test "CoreV2User".
     */
    public function testCoreV2User()
    {
    }

    /**
     * Test attribute "_links".
     */
    public function testPropertyLinks()
    {
    }

    /**
     * Test attribute "id".
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "created".
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "changed".
     */
    public function testPropertyChanged()
    {
    }

    /**
     * Test attribute "username".
     */
    public function testPropertyUsername()
    {
    }

    /**
     * Test attribute "name".
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "admin".
     */
    public function testPropertyAdmin()
    {
    }

    /**
     * Test attribute "namespace".
     */
    public function testPropertyNamespace()
    {
    }

    /**
     * Test attribute "locale".
     */
    public function testPropertyLocale()
    {
    }

    /**
     * Test attribute "auth".
     */
    public function testPropertyAuth()
    {
    }

    /**
     * Test attribute "has_password".
     */
    public function testPropertyHasPassword()
    {
    }

    /**
     * Test attribute "hard_quota".
     */
    public function testPropertyHardQuota()
    {
    }

    /**
     * Test attribute "soft_quota".
     */
    public function testPropertySoftQuota()
    {
    }

    /**
     * Test attribute "available".
     */
    public function testPropertyAvailable()
    {
    }

    /**
     * Test attribute "used".
     */
    public function testPropertyUsed()
    {
    }
}
