<?php

declare(strict_types=1);

/**
 * balloon
 *
 * @copyright   Copryright (c) 2019 gyselroth GmbH (https://gyselroth.com)
 * @license     MIT https://opensource.org/licenses/MIT
 */

/**
 * balloon API.
 *
 * balloon API
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Balloon\Sdk;

/**
 * CoreV2EventLogClientTest Class Doc Comment.
 *
 * @category    Class
 * @description Describes the client from which the operation was executed.
 *
 * @author      Swagger Codegen team
 *
 * @see        https://github.com/swagger-api/swagger-codegen
 */
class CoreV2EventLogClientTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Setup before running any test case.
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()
    {
    }

    /**
     * Test "CoreV2EventLogClient".
     */
    public function testCoreV2EventLogClient()
    {
    }

    /**
     * Test attribute "type".
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "app".
     */
    public function testPropertyApp()
    {
    }

    /**
     * Test attribute "v".
     */
    public function testPropertyV()
    {
    }

    /**
     * Test attribute "hostname".
     */
    public function testPropertyHostname()
    {
    }
}
