<?php
/**
 * DeltaTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Balloon\Sdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * balloon API
 *
 * balloon API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Balloon\Sdk;

/**
 * DeltaTest Class Doc Comment
 *
 * @category    Class
 * @description The delta is a differential feed to get changes since the last delta call.
 * @package     Balloon\Sdk
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DeltaTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Delta"
     */
    public function testDelta()
    {
    }

    /**
     * Test attribute "reset"
     */
    public function testPropertyReset()
    {
    }

    /**
     * Test attribute "cursor"
     */
    public function testPropertyCursor()
    {
    }

    /**
     * Test attribute "has_more"
     */
    public function testPropertyHasMore()
    {
    }

    /**
     * Test attribute "nodes"
     */
    public function testPropertyNodes()
    {
    }
}
