<?php

declare(strict_types=1);

/**
 * balloon
 *
 * @copyright   Copryright (c) 2019 gyselroth GmbH (https://gyselroth.com)
 * @license     MIT https://opensource.org/licenses/MIT
 */

/**
 * balloon API.
 *
 * balloon API
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Balloon\Sdk;

/**
 * NotificationV2NotificationSenderTest Class Doc Comment.
 *
 * @category    Class
 * @description Points to the message. If there is no sender (For example the message came from the system itself) this is null.
 *
 * @author      Swagger Codegen team
 *
 * @see        https://github.com/swagger-api/swagger-codegen
 */
class NotificationV2NotificationSenderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Setup before running any test case.
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()
    {
    }

    /**
     * Test "NotificationV2NotificationSender".
     */
    public function testNotificationV2NotificationSender()
    {
    }

    /**
     * Test attribute "id".
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name".
     */
    public function testPropertyName()
    {
    }
}
