<?php

declare(strict_types=1);

/**
 * balloon
 *
 * @copyright   Copryright (c) 2019 gyselroth GmbH (https://gyselroth.com)
 * @license     MIT https://opensource.org/licenses/MIT
 */

/**
 * balloon API.
 *
 * balloon API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Balloon\Sdk;

use PHPUnit\Framework\TestCase;

/**
 * NotificationV2NotificationTest Class Doc Comment.
 *
 * @category    Class
 * @description A notification
 *
 * @author      OpenAPI Generator team
 *
 * @see        https://openapi-generator.tech
 */
class NotificationV2NotificationTest extends TestCase
{
    /**
     * Setup before running any test case.
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()
    {
    }

    /**
     * Test "NotificationV2Notification".
     */
    public function testNotificationV2Notification()
    {
    }

    /**
     * Test attribute "_links".
     */
    public function testPropertyLinks()
    {
    }

    /**
     * Test attribute "id".
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "created".
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "locale".
     */
    public function testPropertyLocale()
    {
    }

    /**
     * Test attribute "subject".
     */
    public function testPropertySubject()
    {
    }

    /**
     * Test attribute "message".
     */
    public function testPropertyMessage()
    {
    }

    /**
     * Test attribute "sender".
     */
    public function testPropertySender()
    {
    }

    /**
     * Test attribute "node".
     */
    public function testPropertyNode()
    {
    }
}
