<?php

declare(strict_types=1);

/**
 * balloon
 *
 * @copyright   Copryright (c) 2019 gyselroth GmbH (https://gyselroth.com)
 * @license     MIT https://opensource.org/licenses/MIT
 */

/**
 * balloon API.
 *
 * balloon API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Balloon\Sdk;

use PHPUnit\Framework\TestCase;

/**
 * OfficeV2WopiDocumentTest Class Doc Comment.
 *
 * @category    Class
 * @description WOPI document https://wopi.readthedocs.io/projects/wopirest/en/latest/files/CheckFileInfo.html
 *
 * @author      OpenAPI Generator team
 *
 * @see        https://openapi-generator.tech
 */
class OfficeV2WopiDocumentTest extends TestCase
{
    /**
     * Setup before running any test case.
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()
    {
    }

    /**
     * Test "OfficeV2WopiDocument".
     */
    public function testOfficeV2WopiDocument()
    {
    }

    /**
     * Test attribute "base_file_name".
     */
    public function testPropertyBaseFileName()
    {
    }

    /**
     * Test attribute "size".
     */
    public function testPropertySize()
    {
    }

    /**
     * Test attribute "version".
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "owner_id".
     */
    public function testPropertyOwnerId()
    {
    }

    /**
     * Test attribute "user_id".
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "user_friendly_name".
     */
    public function testPropertyUserFriendlyName()
    {
    }

    /**
     * Test attribute "user_can_write".
     */
    public function testPropertyUserCanWrite()
    {
    }

    /**
     * Test attribute "post_message_origin".
     */
    public function testPropertyPostMessageOrigin()
    {
    }
}
