<?php

declare(strict_types=1);

/**
 * balloon
 *
 * @copyright   Copryright (c) 2019 gyselroth GmbH (https://gyselroth.com)
 * @license     MIT https://opensource.org/licenses/MIT
 */

/**
 * balloon API.
 *
 * balloon API
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Balloon\Sdk;

/**
 * UserTest Class Doc Comment.
 *
 * @category    Class
 * @description A user is used to access the server.
 *
 * @author      Swagger Codegen team
 *
 * @see        https://github.com/swagger-api/swagger-codegen
 */
class UserTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Setup before running any test case.
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()
    {
    }

    /**
     * Test "User".
     */
    public function testUser()
    {
    }

    /**
     * Test attribute "_links".
     */
    public function testPropertyLinks()
    {
    }

    /**
     * Test attribute "id".
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "created".
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "changed".
     */
    public function testPropertyChanged()
    {
    }

    /**
     * Test attribute "username".
     */
    public function testPropertyUsername()
    {
    }

    /**
     * Test attribute "name".
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "admin".
     */
    public function testPropertyAdmin()
    {
    }

    /**
     * Test attribute "namespace".
     */
    public function testPropertyNamespace()
    {
    }

    /**
     * Test attribute "locale".
     */
    public function testPropertyLocale()
    {
    }

    /**
     * Test attribute "auth".
     */
    public function testPropertyAuth()
    {
    }

    /**
     * Test attribute "hard_quota".
     */
    public function testPropertyHardQuota()
    {
    }

    /**
     * Test attribute "soft_quota".
     */
    public function testPropertySoftQuota()
    {
    }

    /**
     * Test attribute "available".
     */
    public function testPropertyAvailable()
    {
    }

    /**
     * Test attribute "used".
     */
    public function testPropertyUsed()
    {
    }
}
